### ISSUE TITLE
 taylored param.h90 for visualization

### ISSUE THREAD

**Issue by rabarbar42** [Multiphysics-Flow-Solvers/FluTAS#2]
Hello.
It's sorta kinda a feature request, but please consider, for the 'examples' folder, to taylor the param.h90 so that it fits what's in the dns.in for each example.
It is natural, that we the new users, will want to check out the examples and then take a look in Paraview, but w/o the aforementioned paratemters matching, that's not trivial.  I enclose the dns.in I used, long with the param.h90 I made for it (in the end, it did not work).

**Comment by p-costa** [comment]
Thanks for the feedback!

We could settle this issue swiftly by porting the visualization workflow in CaNS to here, to replace these old routines. 

Leaving here the links for future reference: [1](https://github.com/p-costa/CaNS/blob/master/src/INFO_VISU.md), [2](https://github.com/p-costa/CaNS/tree/master/utils/visualize_fields/gen_xdmf_easy).

**Comment by rabarbar42** [comment]
Hello thank you very much I will test it ASAP

**Comment by p-costa** [comment]
Hi,

#3 merged to the code the approach for visualizing field data mentioned in https://github.com/Multiphysics-Flow-Solvers/FluTAS/issues/2#issuecomment-948772713.

It's quite easy to use it (one needs `python3` and `numpy`):

1. copy the file under `utils/visualize_fields/gen_xdmf_easy/write_xdmf.py` to the data folder
2. run the XDMF generator `python write_xdmf.py` and hit enter three times to enter the default values.
3. done! `paraview viewfld_DNS.xmf` will allow you to visualize the field.

This approach has several advantages to the old method:

* The physical time is accurately preserved in the metadata (`.xdf`) file
* Vector fields are automatically detected and lumped together
* Much simpler workflow w/ no need to input by hand the computational setup
* ... and still one single `.xdf` file per time series, per geometry

More info in the revised [INFO_VISU.md](https://github.com/Multiphysics-Flow-Solvers/FluTAS/blob/main/INFO_VISU.md).

PS: to be able to visualize the data, you'd need to re-do the simulations with the new `main` branch.

**Comment by p-costa** [comment]
This seems settled, so I'll go ahead and close this. But please feel free to reopen if you experience issues. Thanks, @rabarbar42 @nscapin!
